### ISSUE TITLE
reuse functions

### ISSUE THREAD

**Issue by aleks-hyf** [SwathiSankararaman/hyf-homework#10]
https://github.com/SwathiSankararaman/hyf-homework/blob/62ec913d8eee3a014399a675fe117fc27dad1d65/javascript/javascript2/week1/diffMedian%26Avg.js#L34

You should be calling existing functions for average and median instead of copy/pasting their content. For example, if you find an error in "median", you now have to fix it twice.

**Comment by SwathiSankararaman** [comment]
Modified the code based on the feedback
