### ISSUE TITLE
map & filter

### ISSUE THREAD

**Issue by aleks-hyf** [SwathiSankararaman/hyf-homework#12]
https://github.com/SwathiSankararaman/hyf-homework/blob/62ec913d8eee3a014399a675fe117fc27dad1d65/javascript/javascript2/week1/shortestWord.js#L10

Obviously this homework would have been easier with map and filter, so next time you could do it like that.

**Comment by SwathiSankararaman** [comment]
Yes Sure. Since I did not know map and filter before I used for loop. From next time is going to be map and filter.
