### ISSUE TITLE
This will not even work

### ISSUE THREAD

**Issue by aleksd-dfds** [SwathiSankararaman/hyf-homework#15]
https://github.com/SwathiSankararaman/hyf-homework/blob/404459efb8ad32ee1b04aa25a874e85d939566d2/javascript/javascript2/week2/doublingOfNumbers.js#L13

Bonus points if you figure out what's wrong with this code.

**Comment by SwathiSankararaman** [comment]
Yes I think I figured out. It should be 
 newNumbers.push(numbers[i] * 2);
Right ?

**Comment by SwathiSankararaman** [comment]
newNumbers.push(numbers[i] * 2);

**Comment by aleksd-dfds** [comment]
Yes indeed. The arrays are not the same size, so indexing with [i] is incorrect. It will actually produce a weird array with some missing elements in it. .push will work just fine. Merry Xmas!
