### ISSUE TITLE
Unnecessary parens again

### ISSUE THREAD

**Issue by aleksd-dfds** [SwathiSankararaman/hyf-homework#17]
https://github.com/SwathiSankararaman/hyf-homework/blob/404459efb8ad32ee1b04aa25a874e85d939566d2/javascript/javascript2/week2/workingWithMovies.js#L44

You will be more confident about what gets evaluated first if you read this:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

**Comment by SwathiSankararaman** [comment]
Sure. Thank you for sharing and did changes in my code
