### ISSUE TITLE
Solid use of reduce

### ISSUE THREAD

**Issue by aleksd-dfds** [SwathiSankararaman/hyf-homework#20]
https://github.com/SwathiSankararaman/hyf-homework/blob/404459efb8ad32ee1b04aa25a874e85d939566d2/javascript/javascript2/week2/workingWithMovies.js#L68

It's good to understand how reduce works. Also nice initialization at the end. 
Not a criticism, but if my reduce spans 10 lines, i would just turn it back into a for loop for readability.

**Comment by SwathiSankararaman** [comment]
Yes thats true. I completely agree. From next time I will try to have this in my mind before trying to decide for loop or reduce.
