### ISSUE TITLE
commonFunctionality

### ISSUE THREAD

**Issue by aleks-hyf** [SwathiSankararaman/hyf-homework#8]
https://github.com/SwathiSankararaman/hyf-homework/blob/62ec913d8eee3a014399a675fe117fc27dad1d65/javascript/javascript2/week1/animalNameGenerator.js#L34

You're using the same commonFunctionality with no arguments in 3 places, then there is no point in having those 3 functions checking for the type. Save yourself (and the next programmer) the headache of trying to understand why they're there.

**Comment by aleks-hyf** [comment]
e.g.: 
document.getElementById('name').addEventListener('mouseover', commonFunctionality);
document.getElementById('name').addEventListener('hover', commonFunctionality);

**Comment by SwathiSankararaman** [comment]
Implemented the feedback
