### ISSUE TITLE
simplify logic

### ISSUE THREAD

**Issue by aleks-hyf** [SwathiSankararaman/hyf-homework#9]
https://github.com/SwathiSankararaman/hyf-homework/blob/62ec913d8eee3a014399a675fe117fc27dad1d65/javascript/javascript2/week1/diffMedian%26Avg.js#L22

Factor out arrayLength/2 into a new variable. Also, shouldn't you be dividing this sum by 2 to make the average?

**Comment by SwathiSankararaman** [comment]
Modified the logic based on the feedback
